services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /docs
    volumes:
      - ./:/docs
    ports:
      - "8002:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    command: mkdocs serve -a 0.0.0.0:8000 --livereload --watch docs --dirtyreload